### ISSUE TITLE
Support firewall rules as a resource

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/terraform-provider-oxide#219]
Unlike other resources, the firewall rules for a particular VPC are meant to be CRUD as a single unit (e.g. the two rules that make up "allow http access to this port 8000-8080 except for port 8123" have to be applied together). As such, the API for firewall rules cover only list and replace actions. When implemented as a Terraform resource, firewall rule request payload is expected to include the entire rule set instead of individual rules to add to / remove from the existing firewall rules. This means any system-generated default VPC firewall rules intended to be kept should be included in the request payload. For example, if user wants to open up the http access as stated above on top of the default VPC rules, they need to specify something like this: 
```
  allow {
    name = "allow-icmp"
    direction = "inbound"
    protocol = "icmp"
    priority = 65534
  }

  allow {
    name = "allow-internal-inbound"
    direction = "inbound"
    priority = 65534
    hosts = [
      {
         type = "vpc"
         name = "default"
      }
    ]
    targets = [
      {
         type = "vpc"
         name = "default"
      }
    ]
  }

  allow {
    name = "allow-ssh"
    direction = "inbound"
    protocol = "tcp"
    ports    = ["22"]
    priority = 65534
  }

  allow {
    name = "custom-allow-http"
    direction = "inbound"
    protocol = "tcp"
    ports    = ["8000-8080"]
    priority = 100
  }

  deny {
    name = "custom-deny-http"
    direction = "inbound"
    protocol = "tcp"
    ports    = ["8123"]
    priority = 50
  }
```
This is still consistent with the Terraform convention which expects user to specify the **end state** in the plan.

cc @karencfv for any open questions or concerns (in case the above hasn't adequately addressed what we discussed a while back).

**Comment by karencfv** [comment]
Thanks @askfongjojo for following up on this!

> When implemented as a Terraform resource, firewall rule request payload is expected to include the entire rule set instead of individual rules to add to / remove from the existing firewall rules

Great, this simplifies things a lot!

Regarding the block schema, it's generally preferable to keep it as close as possible to the shape of the API. I'm thinking something more along the lines of:

```hcl
rules = [
   {
    action = "deny"
    name = "custom-deny-http"
    direction = "inbound"
    protocol = "tcp"
    ports    = ["8123"]
    priority = 50
  },
  {
    action = "allow"
    name = "allow-internal-inbound"
    direction = "inbound"
    priority = 65534
    hosts = [
      {
         type = "vpc"
         name = "default"
      }
    ]
    targets = [
      {
         type = "vpc"
         name = "default"
      }
    ]
  }
]
```
