### ISSUE TITLE
oxide_image does not accept source_url as documented.

### ISSUE THREAD

**Issue by arctiqmk2** [oxidecomputer/terraform-provider-oxide#252]
### Preliminary checks

- [X] I am using the latest version, or the latest version that corresponds to my Oxide installation.
- [X] There is no open issue that reports the same problem.

### What was the expected behaviour

Using the following terraform, the expected outcome to be a deployed image within the project.  This expectation is set via the documentation here: https://github.com/oxidecomputer/terraform-provider-oxide/blob/main/docs/resources/oxide_image.md#example-usage

It is in the **Example Usage** text that it implies that `source_url` is a valid resource variable.

> To create an image it's necessary to define its source by setting one of `source_url` or `source_snapshot_id`.

```terraform
resource "oxide_image" "testing_image" {
  project_id         = oxide_project.testing_project.id
  description        = "test image"
  name               = "debian-12-genericcloud-amd64"
  source_url	     = "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.raw"
  block_size	     = "512"
  os                 = "debian"
  version            = "12"
  timeouts = {
    read   = "1m"
    create = "3m"
  }
}
```

### What is the current behaviour and what actions did you take to get there

When the above terraform is applied, the following error is emitted:

```shell
oxide_image.testing_image: Creating...
╷
│ Error: Error creating image
│
│   with oxide_image.testing_image,
│   on main.tf line 29, in resource "oxide_image" "testing_image":
│   29: resource "oxide_image" "testing_image" {
│
│ API error: HTTP 400
│ (https://[REDACTED].sys.r3.oxide-preview.com/v1/images?project=98fa859f-c671-4e7b-acc1-42575221c2cd) BODY
│ -> {
│   "request_id": "4b254610-29f7-4c4c-a477-d25503701d89",
│   "message": "unable to parse JSON body: source.type: unknown variant `url`, expected `snapshot` or `you_can_boot_anything_as_long_as_its_alpine` at line 1 column 119"
│ }
```

### Provider version

0.1.0-beta

### Terraform version

Terraform v1.6.6

### Operating system

MacOS 14.2.1

### Anything else you would like to add?

The digest object appears to be read-only, it would be good to include it as an optional input to the resource definition and reject the resource if the snapshot or URL does not match the intended digest.

Suggesting something like:
```terraform
digest_algorithm = "sha256" 
digest_hash = "b84ababbfd9b720f2dfdf3e33d141b2b038bdcc6feaa51bd702ffe45566bfbc3"
```

I think it is possible that the documentation reflects an original design intention to include `source_url` though perhaps it was never implemented.

**Comment by karencfv** [comment]
@arctiqmk2, thanks a bunch for taking the time to write this detailed bug report.

We recently updated to a newer version of the provider to `0.1.0`, and the rack you are targeting was also updated to contain a newer version of the API.

In this version, creating images via URL is no longer supported. We have several changes which you can find in our [changelog](https://github.com/oxidecomputer/terraform-provider-oxide/blob/main/CHANGELOG.md).

Looks like I completely missed editing that sentence in the docs when [I removed URL support](https://github.com/oxidecomputer/terraform-provider-oxide/pull/228/files#diff-1be43bac85cb24ce2732f23d2011c520f584df8a5b29f7213241239f648bddba) from the docs. Sorry about that!! I'll fix it right away :)
