### ISSUE TITLE
Support for attaching floating IP in instance creation payload 

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/terraform-provider-oxide#256]
### Overview

Instance external IP now permits multiple addresses and one of which can be a floating IP address (see https://docs.oxide.computer/guides/managing-floating-ips for more context).

**Comment by karencfv** [comment]
Thanks for opening this issue @askfongjojo! I managed to squeeze this feature in before releasing the provider https://github.com/oxidecomputer/terraform-provider-oxide/pull/230

Here are the docs https://registry.terraform.io/providers/oxidecomputer/oxide/latest/docs/resources/oxide_instance#nested-schema-for-external_ips

I'll close this issue unless you think there's something I'm missing here?

**Comment by askfongjojo** [comment]
The docs lgtm. Being able to specify `type` = "floating" and the name of the floating ip address should be all that is needed from the payload perspective. Thank you for the quick turnaround!

**Comment by karencfv** [comment]
Awesome! I'll close this issue then as completed
