### ISSUE TITLE
`ssh_keys` instead of `ssh_public_keys` is still being referenced in docs and changelog

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/terraform-provider-oxide#281]
### Preliminary checks

- [X] I am using the latest version, or the latest version that corresponds to my Oxide installation.
- [X] There is no open issue that reports the same problem.

### What was the expected behaviour

I think the attribute `ssh_public_keys` was renamed at some point but we have docs (e.g. `docs/resources/oxide_instance.md` and v0.2.0 CHANGELOG.md) still referencing it as `ssh_keys`. I used the old name initially and was confused for a bit.

### What is the current behaviour and what actions did you take to get there

(see above)

### Provider version

0.2.0

### Terraform version

1.4.4

### Operating system

MacOS

**Comment by karencfv** [comment]
oops! I'll fix that
