### ISSUE TITLE
Support for IP pool as a resource

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/terraform-provider-oxide#335]
### Overview

The resource was scoped out during v1 (#103) but we just got a request from a customer to be able to script their deployment plans that include IP pool (and IP range) add/remove operations.

### Anything else you would like to add?

@internet-diglett - Would this happen to be among the TF enhancements you are working on?

**Comment by karencfv** [comment]
This one should be relatively easy to add as I already had it before. I can take this one :)
